### ISSUE TITLE
mediawiki syntax highlighter error

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#522]
https://pandorabox.io/index.php/Digiline_Jumpdrive_controller

```
[28cb5617f5328279c2a26a8e] /index.php/Digiline_Jumpdrive_controller Error from line 300 of /var/www/html/extensions/SyntaxHighlight_GeSHi/includes/SyntaxHighlight.php: Call to undefined method ObjectCache::getMainWANInstance()

Backtrace:

#0 /var/www/html/extensions/SyntaxHighlight_GeSHi/includes/SyntaxHighlight.php(116): SyntaxHighlight::highlight(string, string, array)
#1 /var/www/html/includes/parser/Parser.php(4293): SyntaxHighlight::parserHook(string, array, Parser, PPFrame_Hash)
#2 /var/www/html/includes/parser/PPFrame_Hash.php(328): Parser->extensionSubstitution(array, PPFrame_Hash)
#3 /var/www/html/includes/parser/Parser.php(3330): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#4 /var/www/html/includes/parser/Parser.php(1489): Parser->replaceVariables(string)
#5 /var/www/html/includes/parser/Parser.php(593): Parser->internalParse(string)
#6 /var/www/html/includes/content/WikitextContent.php(368): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#7 /var/www/html/includes/content/AbstractContent.php(555): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#8 /var/www/html/includes/Revision/RenderedRevision.php(264): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#9 /var/www/html/includes/Revision/RenderedRevision.php(236): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#10 /var/www/html/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#11 /var/www/html/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#12 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#13 /var/www/html/includes/Revision/RenderedRevision.php(198): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#14 /var/www/html/includes/poolcounter/PoolWorkArticleView.php(196): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#15 /var/www/html/includes/poolcounter/PoolCounterWork.php(125): PoolWorkArticleView->doWork()
#16 /var/www/html/includes/page/Article.php(791): PoolCounterWork->execute()
#17 /var/www/html/includes/actions/ViewAction.php(63): Article->view()
#18 /var/www/html/includes/MediaWiki.php(511): ViewAction->show()
#19 /var/www/html/includes/MediaWiki.php(302): MediaWiki->performAction(Article, Title)
#20 /var/www/html/includes/MediaWiki.php(900): MediaWiki->performRequest()
#21 /var/www/html/includes/MediaWiki.php(527): MediaWiki->main()
#22 /var/www/html/index.php(44): MediaWiki->run()
#23 {main}

```

**Comment by BuckarooBanzay** [comment]
updated to newest highlighter
https://github.com/wikimedia/mediawiki-extensions-SyntaxHighlight_GeSHi
